# from . import pf_template
from . import (
    res_partner,
    contact_info_client_type,
    contact_info_motives,
    contact_info_what_is_your_cms,
    contact_info_use_in_work,
    contact_info_receive_leads,
    contact_info_bonus_for_recom,
    additional_info_partner,
    crm_lead,
    control_next_opportunity,
    payment_payment_method,
    payment_form_of_payment,
    sale_order,
    traffic_source,
    deal_type,
    contact_info_what_departments,
    contact_info_what_is_important,
    contact_info_license_now,
    contact_info_license_buy,
    contact_info_portal_address,
    contact_info_cooper_term,
    contact_info_what_services,
)
