{
    "name": "Contacts custom fields contacts",
    "license": "LGPL-3",
    "version": "14.0.2.0.1",
    "author": "YevdokimovA",
    "application": "True",
    "depends": [
        "base",
        "web",
        "crm",
        "sale",
        "project",
        "hr_recruitment",
        "hr_timesheet_task_domain",
        "hr_timesheet_task_stage",
        "web_ir_actions_act_multi",
        "web_ir_actions_act_view_reload",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/res_partner_view.xml",
        "views/contact_info_client_type_view.xml",
        "views/contact_info_motives_view.xml",
        "views/contact_info_what_is_your_cms_view.xml",
        "views/contact_info_use_in_work_view.xml",
        "views/contact_info_receive_leads_view.xml",
        "views/contact_info_bonus_for_recom_view.xml",
        "views/additional_info_partner_view.xml",
        "views/crm_lead_view.xml",
        "views/control_next_opportunity_view.xml",
        "views/payment_payment_method_view.xml",
        "views/payment_form_of_payment_view.xml",
        "views/traffic_source_view.xml",
        "views/deal_type_view.xml",
        "views/sale_order_view.xml",
        "views/contact_info_what_departments_view.xml",
        "views/contact_info_what_is_important_view.xml",
        "views/contact_info_license_now_view.xml",
        "views/contact_info_license_buy_view.xml",
        "views/contact_info_portal_address_view.xml",
        "views/contact_info_cooper_term_view.xml",
        "views/contact_info_what_services_view.xml",
        "views/project_task_view.xml",
        "views/project_project_view.xml",
        "views/hr_applicant_view.xml",
        "views/hr_position_view.xml",
        "views/hr_timesheet_switch_form.xml",
    ],
    "installable": True,
}
