name: Pre-commit

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - synchronize
        branches:
            - master
            - main
            - dev

jobs:
    pre-commit:
        uses: BorovlevAS/ci_cd_workflows/.github/workflows/precommit.yml@main
